ALTER TABLE "Opportunity"
ADD COLUMN "operationCode" TEXT,
ADD COLUMN "wonAt" TIMESTAMP(3),
ADD COLUMN "operationalStatus" TEXT;

ALTER TABLE "Quote"
ADD COLUMN "costSubtotal" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "profit" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "marginPercent" DECIMAL(65,30) NOT NULL DEFAULT 0;

ALTER TABLE "QuoteItem"
ADD COLUMN "unitCost" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "totalCost" DECIMAL(65,30) NOT NULL DEFAULT 0;

ALTER TABLE "ServiceItem"
ADD COLUMN "cost" DECIMAL(65,30) NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX "Opportunity_operationCode_key" ON "Opportunity"("operationCode");
